use schemas::typed::{AppSchema, NumericType, PrimitiveType, StoreSerialized, TypeKind};

#[derive(Debug)]
pub struct TypeScriptCodegen {
    pub(crate) schema: AppSchema,
}

impl TypeScriptCodegen {
    pub fn new(schema: AppSchema) -> Self {
        Self { schema }
    }

    pub fn emit(&self) -> String {
        let mut output = String::new();

        output.push_str("// This file is generated by maf. Do not edit manually.\n");

        output.push_str("export type MafStoresList = {\n");
        for store in &self.schema.stores {
            output.push_str(&self.indent(self.emit_store(store)));
            output.push_str("\n");
        }
        output.push_str("};\n");

        output.push_str(
            r#"export type GeneratedTypes = {
  stores: MafStoresList;        
};
"#,
        );

        output
    }

    /// Adds one level of indentation to every line of the given string.
    fn indent(&self, input: impl AsRef<str>) -> String {
        input
            .as_ref()
            .lines()
            .map(|line| format!("  {}", line))
            .collect::<Vec<_>>()
            .join("\n")
    }

    pub(super) fn format_type(&self, kind: &TypeKind) -> String {
        match kind {
            TypeKind::Primitive(PrimitiveType::String)
            | TypeKind::Primitive(PrimitiveType::Char) => "string".to_string(),
            TypeKind::Primitive(PrimitiveType::Numeric(NumericType::I64 | NumericType::U64)) => {
                "bigint".to_string()
            }
            TypeKind::Primitive(PrimitiveType::Numeric(..)) => "number".to_string(),
            TypeKind::Primitive(PrimitiveType::Bool) => "boolean".to_string(),
            TypeKind::Primitive(PrimitiveType::Unit) => "void".to_string(),

            TypeKind::Nullable(inner) => {
                let inner_type = self.format_type(inner);
                format!("{} | null", inner_type)
            }

            TypeKind::Record(record) => {
                format!(
                    "{{\n{};\n}}",
                    record
                        .fields
                        .iter()
                        .map(|(key, value)| format!("{}: {}", key, self.format_type(value)))
                        .map(|line| self.indent(&line))
                        .collect::<Vec<_>>()
                        .join(";\n")
                )
            }
        }
    }

    fn emit_store(&self, store: &StoreSerialized) -> String {
        let mut output = String::new();

        output.push_str(&format!("\"{}\": {{\n", store.name));
        output.push_str(&self.indent(format!("name: \"{}\";", store.name.replace("\"", "\\\""))));
        output.push_str("\n");
        output.push_str(&self.indent(format!("select: {};", self.format_type(&store.select))));
        output.push_str("\n};");

        output
    }
}

#[cfg(test)]
mod tests {
    use facet::Facet;
    use maf::StoreData;
    use serde::Serialize;

    use super::*;

    fn store_to_schema<T: StoreData>() -> StoreSerialized {
        StoreSerialized {
            name: T::name().as_ref().to_string(),
            select: TypeKind::from(T::Select::SHAPE),
        }
    }

    #[derive(Serialize, Facet)]
    pub struct Pomodoro {
        pub phase: String,
        pub count: u32,
        pub auto: bool,
        pub durations: PomodoroDurations,
    }

    #[derive(Serialize, Facet)]
    #[facet(rename_all = "camelCase")]
    pub struct PomodoroDurations {
        pub hustle: u32,
        pub rest: u32,
        pub long_rest: u32,
    }

    impl StoreData for Pomodoro {
        type Select<'this> = &'this Pomodoro;

        fn init() -> Self {
            Self {
                phase: "hustle".to_string(),
                count: 0,
                auto: false,
                durations: PomodoroDurations {
                    hustle: 25 * 60,
                    rest: 5 * 60,
                    long_rest: 15 * 60,
                },
            }
        }

        fn name() -> impl AsRef<str> + Send {
            "pomodoro"
        }

        fn select(&self, _user: &maf::User) -> Self::Select<'_> {
            self
        }
    }

    #[test]
    fn typescript_type_format() {
        let codegen = TypeScriptCodegen {
            schema: AppSchema {
                rpcs: vec![],
                stores: vec![],
            },
        };

        assert_eq!(
            codegen.format_type(&TypeKind::Primitive(PrimitiveType::String)),
            "string"
        );
        assert_eq!(
            codegen.format_type(&TypeKind::Primitive(PrimitiveType::Numeric(
                NumericType::I64
            ))),
            "bigint"
        );
        assert_eq!(
            codegen.format_type(&TypeKind::Primitive(PrimitiveType::Bool)),
            "boolean"
        );
        assert_eq!(
            codegen.format_type(&TypeKind::Nullable(Box::new(TypeKind::Primitive(
                PrimitiveType::String
            )))),
            "string | null"
        );

        assert_eq!(
            codegen.format_type(&TypeKind::Record(Box::new(schemas::typed::RecordType {
                fields: vec![
                    (
                        "name".to_string(),
                        TypeKind::Primitive(PrimitiveType::String)
                    ),
                    (
                        "number".to_string(),
                        TypeKind::Primitive(PrimitiveType::Numeric(NumericType::F64))
                    )
                ],
            }))),
            r#"{
  name: string;
  number: number;
}"#
        )
    }

    #[test]
    fn typescript_codegen_store() {
        let codegen = TypeScriptCodegen {
            schema: AppSchema {
                stores: vec![],
                rpcs: vec![],
            },
        };

        println!("{}", codegen.emit_store(&store_to_schema::<Pomodoro>()));

        assert_eq!(
            codegen.emit_store(&store_to_schema::<Pomodoro>()),
            r#""pomodoro": {
  name: "pomodoro";
  select: {
    phase: string;
    count: number;
    auto: boolean;
    durations: {
      hustle: number;
      rest: number;
      longRest: number;
    };
  };
};"#
        );
    }
}
