use schemas::typed::{AppSchema, NumericType, PrimitiveType, StoreSerialized, TypeKind};

#[derive(Debug)]
pub struct TypeScriptCodegen {
    pub(crate) schema: AppSchema,
}

impl TypeScriptCodegen {
    pub fn new(schema: AppSchema) -> Self {
        Self { schema }
    }

    pub fn emit(&self) -> String {
        let mut output = String::new();

        output.push_str("// This file is generated by maf. Do not edit manually.\n\n");

        output.push_str("// prettier-ignore\n");
        output.push_str("export type MafStoresList = {\n");
        for store in &self.schema.stores {
            output.push_str(&self.indent(self.emit_store(store)));
            output.push_str("\n");
        }
        output.push_str("};\n\n");

        output.push_str("// prettier-ignore\n");
        output.push_str("export type MafRpcsList = {\n");
        for rpc in &self.schema.rpcs {
            output.push_str(&self.indent(self.emit_rpc(rpc)));
            output.push_str("\n");
        }
        output.push_str("};\n\n");

        output.push_str(
            r#"export type MafApp = {
  stores: MafStoresList;
  rpcs: MafRpcsList;
};
"#,
        );

        output
    }

    /// Adds one level of indentation to every line of the given string.
    fn indent(&self, input: impl AsRef<str>) -> String {
        input
            .as_ref()
            .lines()
            .map(|line| format!("  {}", line))
            .collect::<Vec<_>>()
            .join("\n")
    }

    pub(super) fn format_type(&self, kind: &TypeKind) -> String {
        match kind {
            TypeKind::Primitive(PrimitiveType::String)
            | TypeKind::Primitive(PrimitiveType::Char) => "string".to_string(),
            TypeKind::Primitive(PrimitiveType::Numeric(NumericType::I64 | NumericType::U64)) => {
                "bigint".to_string()
            }
            TypeKind::Primitive(PrimitiveType::Numeric(..)) => "number".to_string(),
            TypeKind::Primitive(PrimitiveType::Bool) => "boolean".to_string(),
            TypeKind::Primitive(PrimitiveType::Unit) => "void".to_string(),

            TypeKind::Nullable(inner) => {
                let inner_type = self.format_type(inner);
                format!("{} | null", inner_type)
            }

            TypeKind::Record(record) => {
                format!(
                    "{{\n{};\n}}",
                    record
                        .fields
                        .iter()
                        .map(|(key, value)| format!("{}: {}", key, self.format_type(value)))
                        .map(|line| self.indent(&line))
                        .collect::<Vec<_>>()
                        .join(";\n")
                )
            }

            TypeKind::Tuple(tuple) => {
                let type_strings = tuple
                    .elements
                    .iter()
                    .map(|elem| self.format_type(elem))
                    .collect::<Vec<_>>();

                let multilined = type_strings.iter().any(|s| s.contains('\n'));

                if multilined {
                    format!("[\n{}\n]", self.indent(type_strings.join(",\n")))
                } else {
                    format!("[{}]", type_strings.join(", "))
                }
            }

            TypeKind::Map(map) => {
                let key_type = self.format_type(&map.key);
                let value_type = self.format_type(&map.value);
                format!("Record<{}, {}>", key_type, value_type)
            }

            TypeKind::Array(array) => {
                let element_type = self.format_type(&array.element);
                format!("{}[]", element_type)
            }
        }
    }

    fn emit_store(&self, store: &StoreSerialized) -> String {
        let mut output = String::new();

        output.push_str(&format!("\"{}\": {{\n", store.name));
        output.push_str(&self.indent(format!("name: \"{}\";", store.name.replace("\"", "\\\""))));
        output.push_str("\n");
        output.push_str(&self.indent(format!("select: {};", self.format_type(&store.select))));
        output.push_str("\n};");

        output
    }

    fn emit_rpc(&self, rpc: &schemas::typed::RpcSerialized) -> String {
        format!(
            "\"{name}\": {{\n  name: \"{name}\";\n  params: {};\n  result: {};\n}};",
            rpc.params
                .as_ref()
                .map_or("void".to_string(), |p| self.format_type(p)),
            rpc.result
                .as_ref()
                .map_or("void".to_string(), |r| self.format_type(r)),
            name = rpc.name.replace("\"", "\\\"")
        )
    }
}

#[cfg(test)]
mod tests {
    use facet::Facet;
    use maf::StoreData;
    use schemas::typed::TupleType;
    use serde::Serialize;

    use super::*;

    fn store_to_schema<T: StoreData>() -> StoreSerialized {
        StoreSerialized {
            name: T::name().as_ref().to_string(),
            select: TypeKind::from(T::Select::SHAPE),
        }
    }

    #[derive(Serialize, Facet)]
    pub struct Pomodoro {
        pub phase: String,
        pub count: u32,
        pub auto: bool,
        pub durations: PomodoroDurations,
    }

    #[derive(Serialize, Facet)]
    #[facet(rename_all = "camelCase")]
    pub struct PomodoroDurations {
        pub hustle: u32,
        pub rest: u32,
        pub long_rest: u32,
    }

    impl StoreData for Pomodoro {
        type Select<'this> = &'this Pomodoro;

        fn init() -> Self {
            Self {
                phase: "hustle".to_string(),
                count: 0,
                auto: false,
                durations: PomodoroDurations {
                    hustle: 25 * 60,
                    rest: 5 * 60,
                    long_rest: 15 * 60,
                },
            }
        }

        fn name() -> impl AsRef<str> + Send {
            "pomodoro"
        }

        fn select(&self, _user: &maf::User) -> Self::Select<'_> {
            self
        }
    }

    #[test]
    fn typescript_type_format() {
        let codegen = TypeScriptCodegen {
            schema: AppSchema {
                rpcs: vec![],
                stores: vec![],
            },
        };

        assert_eq!(
            codegen.format_type(&TypeKind::Primitive(PrimitiveType::String)),
            "string"
        );
        assert_eq!(
            codegen.format_type(&TypeKind::Primitive(PrimitiveType::Numeric(
                NumericType::I64
            ))),
            "bigint"
        );
        assert_eq!(
            codegen.format_type(&TypeKind::Primitive(PrimitiveType::Bool)),
            "boolean"
        );
        assert_eq!(
            codegen.format_type(&TypeKind::Nullable(Box::new(TypeKind::Primitive(
                PrimitiveType::String
            )))),
            "string | null"
        );

        assert_eq!(
            codegen.format_type(&TypeKind::Record(Box::new(schemas::typed::RecordType {
                fields: vec![
                    (
                        "name".to_string(),
                        TypeKind::Primitive(PrimitiveType::String)
                    ),
                    (
                        "number".to_string(),
                        TypeKind::Primitive(PrimitiveType::Numeric(NumericType::F64))
                    )
                ],
            }))),
            r#"{
  name: string;
  number: number;
}"#
        )
    }

    #[test]
    fn typescript_format_tuple() {
        let codegen = TypeScriptCodegen {
            schema: AppSchema {
                stores: vec![],
                rpcs: vec![],
            },
        };

        assert_eq!(
            codegen.format_type(&TypeKind::Tuple(Box::new(TupleType {
                elements: vec![
                    TypeKind::Primitive(PrimitiveType::String),
                    TypeKind::Primitive(PrimitiveType::Numeric(NumericType::I64))
                ],
            }))),
            "[string, bigint]"
        );

        assert_eq!(
            codegen.format_type(&TypeKind::Tuple(Box::new(TupleType {
                elements: vec![
                    TypeKind::Primitive(PrimitiveType::String),
                    TypeKind::Record(Box::new(schemas::typed::RecordType {
                        fields: vec![
                            (
                                "string".to_string(),
                                TypeKind::Primitive(PrimitiveType::String)
                            ),
                            (
                                "number".to_string(),
                                TypeKind::Primitive(PrimitiveType::Numeric(NumericType::F64))
                            )
                        ]
                    })),
                    TypeKind::Primitive(PrimitiveType::Bool)
                ],
            }))),
            r#"[
  string,
  {
    string: string;
    number: number;
  },
  boolean
]"#
        )
    }

    #[test]
    fn typescript_format_map() {
        let codegen = TypeScriptCodegen {
            schema: AppSchema {
                stores: vec![],
                rpcs: vec![],
            },
        };

        assert_eq!(
            codegen.format_type(&TypeKind::Map(Box::new(schemas::typed::MapType {
                key: TypeKind::Primitive(PrimitiveType::String),
                value: TypeKind::Primitive(PrimitiveType::Numeric(NumericType::I32)),
            }))),
            "Record<string, number>"
        );

        assert_eq!(
            codegen.format_type(&TypeKind::Map(Box::new(schemas::typed::MapType {
                key: TypeKind::Primitive(PrimitiveType::Numeric(NumericType::I32)),
                value: TypeKind::Record(Box::new(schemas::typed::RecordType {
                    fields: vec![
                        (
                            "name".to_string(),
                            TypeKind::Primitive(PrimitiveType::String)
                        ),
                        (
                            "value".to_string(),
                            TypeKind::Primitive(PrimitiveType::Numeric(NumericType::F64))
                        )
                    ]
                })),
            }))),
            "Record<number, {
  name: string;
  value: number;
}>"
        );
    }

    #[test]
    fn typescript_format_array() {
        let codegen = TypeScriptCodegen {
            schema: AppSchema {
                stores: vec![],
                rpcs: vec![],
            },
        };

        assert_eq!(
            codegen.format_type(&TypeKind::Array(Box::new(schemas::typed::ArrayType {
                element: TypeKind::Primitive(PrimitiveType::String),
            }))),
            "string[]"
        );

        assert_eq!(
            codegen.format_type(&TypeKind::Array(Box::new(schemas::typed::ArrayType {
                element: TypeKind::Record(Box::new(schemas::typed::RecordType {
                    fields: vec![
                        (
                            "name".to_string(),
                            TypeKind::Primitive(PrimitiveType::String)
                        ),
                        (
                            "value".to_string(),
                            TypeKind::Primitive(PrimitiveType::Numeric(NumericType::F64))
                        )
                    ]
                })),
            }))),
            "{
  name: string;
  value: number;
}[]"
        );
    }
}
