use std::collections::HashSet;

use anyhow::Context;
use maf_schemas::typed::{AppSchema, StoreSerialized};
use serde_json::Value;

#[derive(Debug)]
pub struct TypeScriptCodegen {
    pub(crate) schema: AppSchema,
    indent: String,
}

impl TypeScriptCodegen {
    pub fn new(schema: AppSchema) -> Self {
        Self {
            schema,
            indent: "  ".to_string(),
        }
    }

    pub fn emit(&self) -> anyhow::Result<String> {
        let mut output = String::new();

        output.push_str("// This file is generated by maf. Do not edit manually.\n\n");

        output.push_str("// prettier-ignore\n");
        output.push_str("export type MafStoresList = {\n");
        for store in &self.schema.stores {
            output.push_str(&self.indent(self.emit_store(store)?));
            output.push_str("\n");
        }
        output.push_str("};\n\n");

        output.push_str("// prettier-ignore\n");
        output.push_str("export type MafRpcsList = {\n");
        for rpc in &self.schema.rpcs {
            output.push_str(&self.indent(self.emit_rpc(rpc)?));
            output.push_str("\n");
        }
        output.push_str("};\n\n");

        output.push_str(
            r#"export type MafApp = {
  stores: MafStoresList;
  rpcs: MafRpcsList;
};
"#,
        );

        Ok(output)
    }

    /// Adds one level of indentation to every line of the given string.
    fn indent(&self, input: impl AsRef<str>) -> String {
        input
            .as_ref()
            .lines()
            .map(|line| format!("{}{}", self.indent, line))
            .collect::<Vec<_>>()
            .join("\n")
    }

    pub(super) fn format_primitive_type(
        &self,
        kind: &str,
        value: Option<&Value>,
    ) -> anyhow::Result<String> {
        Ok(match kind {
            "string" => "string".into(),
            "number" => "number".into(),

            "integer"
                if value.is_some_and(|v| {
                    v.is_object()
                        && v.get("format").is_some_and(|f| {
                            ["int", "uint", "int64", "uint64", "int128", "uint128"]
                                .iter()
                                .any(|&check| check == f.as_str().unwrap_or_default())
                        })
                }) =>
            {
                "bigint".into()
            }

            "integer" => "number".into(),
            "boolean" => "boolean".into(),
            "null" => "null".into(),

            _ => anyhow::bail!("Unsupported primitive type: {}", kind),
        })
    }

    pub(super) fn format_type_kind(&self, kind: &str, value: &Value) -> anyhow::Result<String> {
        if let Ok(primitive_type) = self.format_primitive_type(kind, Some(value)) {
            return Ok(primitive_type);
        }

        Ok(match kind {
            "object" if value.get("additionalProperties").is_some() => {
                let additional_type = value
                    .get("additionalProperties")
                    .expect("'additionalProperties' should exist");

                // Do we care about the keys of patternProperties? The value of patternProperties
                // is always a type describing the type of the record's keys
                let pattern_properties = value
                    .get("patternProperties")
                    .and_then(|v| v.as_object())
                    .map(|obj| obj.values().collect::<Vec<_>>())
                    .unwrap_or_default();

                let additional_type_str = if additional_type.is_boolean() {
                    pattern_properties
                        .iter()
                        .map(|v| self.format_type(v))
                        .collect::<Result<Vec<_>, _>>()?
                        .join(" | ")
                } else {
                    self.format_type(additional_type)?
                };

                format!("Record<string, {additional_type_str}>")
            }

            "object"
                if value
                    .get("properties")
                    .and_then(|v| v.as_object())
                    .is_some() =>
            {
                let required = value
                    .get("required")
                    .and_then(|v| v.as_array())
                    .map(|arr| {
                        HashSet::from_iter(arr.iter().filter_map(|v| v.as_str()).map(String::from))
                    })
                    .unwrap_or(HashSet::new());

                let fields = value
                    .get("properties")
                    .and_then(|v| v.as_object())
                    .expect("'properties' should exist");

                format!("{{\n{};\n}}", {
                    let mut lines = Vec::new();
                    for (key, value) in fields {
                        let ts_type = self.format_type(value)?;
                        let optional = if required.contains(key) { "" } else { "?" };
                        lines.push(format!(
                            "{key}{optional}:{spacing}{ts_type}",
                            // If the first character is a newline, we don't add extra spacing
                            spacing = if ts_type.starts_with('\n') { "" } else { " " },
                        ));
                    }
                    self.indent(lines.join(";\n"))
                })
            }

            // Tuple types are represented as arrays with a fixed number of items
            "array"
                if value.get("minItems") == value.get("maxItems")
                    && value.get("minItems").is_some_and(|v| v.is_number()) =>
            {
                let items = value
                    .get("prefixItems")
                    .and_then(|v| v.as_array())
                    .context("Expected 'prefixItems' to be an array for tuple type")?;

                let item_types = items
                    .iter()
                    .map(|item| self.format_type(item))
                    .collect::<Result<Vec<_>, _>>()?;

                let is_multilined = item_types.iter().any(|s| s.contains('\n'));

                if is_multilined {
                    format!("[\n{}\n]", self.indent(item_types.join(",\n")))
                } else {
                    format!("[{}]", item_types.join(", "))
                }
            }

            "array" => {
                let item_type = self.format_type(
                    value
                        .get("items")
                        .context("Missing 'items' in array schema")?,
                );

                format!("{}[]", item_type?)
            }

            _ => {
                // Handle other types like arrays, objects, etc.
                return Err(anyhow::anyhow!(
                    "Unsupported type '{}' formatting {value:#?}",
                    kind
                ));
            }
        })
    }

    pub(super) fn format_type(&self, value: &Value) -> anyhow::Result<String> {
        #[cfg(test)]
        println!("format_type: {value:#?}");

        // Reference: https://json-schema.org/draft/2020-12/json-schema-core

        // If `type` is an array of types, it means the value can be any of those types.
        if let Some(Value::Array(types)) = value.get("type") {
            let mut type_strings = Vec::new();
            for t in types {
                if let Value::String(kind) = t {
                    let type_string = self.format_type_kind(kind, value)?;
                    type_strings.push(type_string);
                } else {
                    anyhow::bail!("Expected string in 'type' array. Got: {:?}", t);
                }
            }

            // If the type strings are multiple lines, format them like | <type> on each line
            let multilined = type_strings.iter().any(|s| s.contains('\n'));

            if multilined {
                return Ok(self
                    .indent(format!("\n| ",) + &type_strings.join("\n| "))
                    .trim_start_matches(&self.indent)
                    .to_string());
            } else {
                return Ok(type_strings.join(" | "));
            }
        }

        let kind = value
            .get("type")
            .context("Missing 'type' in schema")?
            .as_str()
            .context("'type' in schema is not a string")?;

        self.format_type_kind(kind, value)

        //     TypeKind::Tuple(tuple) => {
        //         let type_strings = tuple
        //             .elements
        //             .iter()
        //             .map(|elem| self.format_type(elem))
        //             .collect::<Vec<_>>();

        //         let multilined = type_strings.iter().any(|s| s.contains('\n'));

        //         if multilined {
        //             format!("[\n{}\n]", self.indent(type_strings.join(",\n")))
        //         } else {
        //             format!("[{}]", type_strings.join(", "))
        //         }
        //     }
    }

    fn emit_store(&self, store: &StoreSerialized) -> anyhow::Result<String> {
        let mut output = String::new();

        output.push_str(&format!("\"{}\": {{\n", store.name));
        output.push_str(&self.indent(format!("name: \"{}\";", store.name.replace("\"", "\\\""))));
        output.push_str("\n");
        output.push_str(&self.indent(format!(
            "select: {};",
            self.format_type(&store.select.as_value())?
        )));
        output.push_str("\n};");

        Ok(output)
    }

    fn emit_rpc(&self, rpc: &maf_schemas::typed::RpcSerialized) -> anyhow::Result<String> {
        Ok(format!(
            "\"{name}\": {{\n  name: \"{name}\";\n  params: {};\n  result: {};\n}};",
            match rpc.params.as_ref() {
                Some(params) => self.format_type(params.as_value())?,
                None => "void".to_string(),
            },
            self.format_type(&rpc.result.as_value())?,
            name = rpc.name.replace("\"", "\\\"")
        ))
    }
}

#[cfg(test)]
mod tests {
    use schemars::{JsonSchema, generate::SchemaSettings};

    fn create_default_codegen() -> super::TypeScriptCodegen {
        let schema = maf_schemas::typed::AppSchema {
            stores: vec![],
            rpcs: vec![],
        };
        super::TypeScriptCodegen::new(schema)
    }

    fn format_schema<T: JsonSchema>() -> String {
        let mut settings = SchemaSettings::default();
        settings.inline_subschemas = true;
        let mut generator = schemars::SchemaGenerator::new(settings);
        let schema = T::json_schema(&mut generator);
        create_default_codegen()
            .format_type(&schema.as_value())
            .unwrap()
    }

    #[allow(dead_code)]
    #[derive(JsonSchema)]
    struct TestObject {
        field1: String,
        field2: i32,
        #[serde(skip_serializing_if = "Option::is_none")]
        field3: Option<bool>,
    }

    #[allow(dead_code)]
    #[derive(JsonSchema)]
    struct NestedObject {
        nested: TestObject,
        optional: Option<TestObject>,
    }

    #[test]
    fn serialize_primitives() {
        assert_eq!(format_schema::<bool>(), "boolean");
        assert_eq!(format_schema::<f64>(), "number");
        assert_eq!(format_schema::<i32>(), "number");
        assert_eq!(format_schema::<u32>(), "number");
        assert_eq!(format_schema::<i64>(), "bigint");
        assert_eq!(format_schema::<u64>(), "bigint");
        assert_eq!(format_schema::<String>(), "string");
        assert_eq!(format_schema::<()>(), "null");
    }

    #[test]
    fn serialize_objects() {
        let expected = r#"{
  field1: string;
  field2: number;
  field3?: boolean | null;
}"#;

        assert_eq!(format_schema::<TestObject>(), expected);

        let expected_nested = r#"{
  nested: {
    field1: string;
    field2: number;
    field3?: boolean | null;
  };
  optional?:
    | {
      field1: string;
      field2: number;
      field3?: boolean | null;
    }
    | null;
}"#;
        assert_eq!(format_schema::<NestedObject>(), expected_nested);
    }

    #[test]
    fn serialize_arrays() {
        assert_eq!(format_schema::<Vec<String>>(), "string[]");
        assert_eq!(format_schema::<Vec<i32>>(), "number[]");
        assert_eq!(
            format_schema::<Vec<TestObject>>(),
            r#"{
  field1: string;
  field2: number;
  field3?: boolean | null;
}[]"#
        );
    }

    #[test]
    fn serialize_hashmaps() {
        assert_eq!(
            format_schema::<std::collections::HashMap<String, i32>>(),
            "Record<string, number>"
        );

        assert_eq!(
            format_schema::<std::collections::HashMap<String, TestObject>>(),
            r#"Record<string, {
  field1: string;
  field2: number;
  field3?: boolean | null;
}>"#
        );

        // NOTE: JSON object keys are always strings, so even if the Rust type uses i32 as key,
        // it will be serialized and typed as string in TypeScript
        assert_eq!(
            format_schema::<std::collections::HashMap<i32, Vec<i32>>>(),
            "Record<string, number[]>"
        );
    }

    #[test]
    fn serialize_options() {
        assert_eq!(format_schema::<Option<String>>(), "string | null");
        assert_eq!(format_schema::<Option<i32>>(), "number | null");
        assert_eq!(
            format_schema::<Option<TestObject>>(),
            r#"
  | {
    field1: string;
    field2: number;
    field3?: boolean | null;
  }
  | null"#
        );
    }

    #[test]
    fn serialize_tuples() {
        assert_eq!(format_schema::<(String, i32)>(), "[string, number]");
        assert_eq!(
            format_schema::<(String, i32, Option<bool>)>(),
            "[string, number, boolean | null]"
        );
        assert_eq!(
            format_schema::<(i32, TestObject)>(),
            r#"[
  number,
  {
    field1: string;
    field2: number;
    field3?: boolean | null;
  }
]"#
        );
    }
}
