name = "counter"
rooms = "AutoCreate" # This will make MAF put all users in a single *room*

# If your build output path is different, adjust the paths accordingly.
[debug]
command = "cargo build --target wasm32-wasip2"
output = "./target/wasm32-wasip2/debug/counter.wasm"

[release]
command = "cargo build --target wasm32-wasip2 --release"
output = "./target/wasm32-wasip2/release/counter.wasm"
