packages:
  - "www"
  - "packages/compiler"
  - "packages/compiler/lib"
  - "packages/compiler/examples/*"
  - "www/demo"
  - "packages/client"
  - "packages/client/examples/*"
  - "packages/react"
  - "packages/react/examples/*"
  - "packages/platform"
  - "benchmarks/counter"
# TODO: Change me!!
publishBranch: "dev"
