// This file is generated by maf. Do not edit manually.

// prettier-ignore
export type MafStoresList = {
  "count": {
    name: "count";
    select: number | null;
  };
  "count_times_two": {
    name: "count_times_two";
    select: number | null;
  };
};

// prettier-ignore
export type MafRpcsList = {
  "increment_counter": {
    name: "increment_counter";
    params: number;
    result: number;
  };
};

export type MafApp = {
  stores: MafStoresList;
  rpcs: MafRpcsList;
};
