[package]
name = "migrations"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "migrations"
path = "src/lib.rs"

[dependencies]
bitflags = { version = "2.9.0", features = ["serde"] }
chrono = { version = "0.4.40", features = ["serde"] }
rand = "0.9.1"
sea-orm = { version = "1.1.10", features = [
    "sqlx-postgres",
    "runtime-tokio-native-tls",
] }
serde = { version = "^1", features = ["derive"] }
tokio = { version = "1.43.0", features = ["full"] }

[dependencies.sea-orm-migration]
version = "1.1.0"
features = ["runtime-tokio-rustls", "sqlx-postgres"]
