[package]
name = "maf_container"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
async-trait = "0.1.88"
anyhow = "^1.0.96"
axum = { version = "0.8.3", features = ["macros", "ws"] }
base64 = "0.22.1"
biscuit = "0.7.0"
bytes = "1.10.1"
futures-util = "0.3.31"
rand = "0.9.1"
tokio = { version = "1.44.2", features = ["full"] }
tokio-util = { version = "0.7.15", features = ["io"] }
maf_schemas = { path = "../maf_schemas" }
serde = { version = "^1", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "^2"
tracing = "0.1.41"
uuid = { version = "1.16.0", features = ["serde", "v4"] }
wasmtime = { version = "44.0.1", features = ["async", "anyhow"] }
wasmtime-wasi = "44.0.1"
wasmtime-wasi-http = "44.0.1"
wasmtime-wasi-io = "44.0.1"
hyper = "1.8.1"
