[package]
name = "maf_container"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.88"
anyhow = "^1.0.96"
bytes = "1.10.1"
tokio = { version = "1.43.0", features = ["full"] }
tokio-util = { version = "0.7.15", features = ["io"] }
tracing = "0.1.41"
uuid = { version = "1.16.0", features = ["serde", "v4"] }
wasmtime = { version = "30.0.2", features = ["async"] }
wasmtime-wasi = "30.0.2"
wasmtime-wasi-io = "30.0.2"
