// This file is generated by cobble. Do not edit manually.

// prettier-ignore
export type CobbleStoresList = {
  "count": {
    name: "count";
    select: number | null;
  };
};

// prettier-ignore
export type CobbleRpcsList = {
  "increment_counter": {
    name: "increment_counter";
    params: number;
    result: number;
  };
};

export type CobbleApp = {
  stores: CobbleStoresList;
  rpcs: CobbleRpcsList;
};
