[package]
name = "cobble_schemas"
version = "0.1.0-alpha.2"
edition = "2024"

license = "MIT"
description = "Cobble Schemas provides shared schemas for Cobble applications and libraries."
homepage = "https://cobble.gilbertz.me"
repository = "https://github.com/giilbert/cobble"
readme = "../../README.md"

[dependencies]
anyhow = "^1.0.96"
axum = { version = "0.8.3", features = ["macros", "ws"], optional = true }
colored = "3.0.0"
rand = "0.9.1"
schemars = "1.0.4"
serde = { version = "^1", features = ["derive", "rc"] }
serde_json = "1.0.140"
tracing = "0.1.41"
uuid = { version = "1.16.0", features = ["serde", "v4"] }

[features]
error-response = ["dep:axum"]
