[package]
name = "maf_cli"
version = "0.1.0-alpha.4"
edition = "2021"
publish = false

[dependencies]
maf_container = { path = "../maf_container" }
maf_typed = { path = "../maf_typed" }
maf_schemas = { path = "../maf_schemas", features = ["error-response"] }

anyhow = "^1.0.96"
async-trait = "0.1.88"
axum = { version = "0.8.3", features = ["macros", "ws"] }
async_zip = { version = "0.0.17", features = ["full"] }
clap = { version = "4.5.36", features = ["derive"] }
colored = "3.0.0"
dialoguer = "0.11.0"
dotenvy = "0.15.7"
futures-util = { version = "0.3.31", features = ["io"] }
include_dir = "0.7.4"
indicatif = "0.17.11"
notify = "8.0.0"
notify-debouncer-full = "0.5.0"
reqwest = { version = "0.12.15", features = ["json", "stream"] }
serde = { version = "^1", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.44.2", features = ["full"] }
tokio-util = "0.7.14"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
url = "2.5.4"
uuid = { version = "1.16.0", features = ["serde", "v4"] }
toml = "0.8.23"
directories = "6.0.0"
