package maf:bindings;

interface bindings {
    use wasi:io/poll@0.2.4.{pollable};

    resource user {
        constructor(id: tuple<u64, u64>);
        get-meta: func() -> result<user-meta>;
        send: func(bytes: list<u8>) -> result;
    }

    record user-meta {
        id: tuple<u64, u64>,
    }

    record request {
        user: user,
        path: string,
    }

    resource future-user {
        subscribe: func() -> result<pollable, listen-error>;
        get: func() -> result<user, listen-error>;
    }

    resource future-request {
        subscribe: func() -> result<pollable, listen-error>;
        get: func() -> result<request, listen-error>;
    }

    variant listen-error {
        already-listening,
        not-ready,
        closed
    }
    
    listen-user: func() -> result<future-user, listen-error>;
    listen-request: func() -> result<future-request, listen-error>;
}

world imports {
    import bindings;

    export init: func() -> result;
}