package maf:bindings;

interface bindings {
    use wasi:io/poll@0.2.4.{pollable};

    variant message {
        binary(list<u8>),
        text(string),
    }

    variant send-error {
        closed,
        buffer-full,
    }

    resource user {
        meta: func() -> user-meta;
        listen-message: func() -> result<future-message, listen-error>;
        send: func(message: message) -> result<_, send-error>;
    }

    record user-meta {
        id: tuple<u64, u64>,
    }

    record request {
        user: user,
        path: string,
    }

    resource future-message {
        subscribe: func() -> result<pollable, listen-error>;
        get: func() -> result<message, listen-error>;
    }

    resource future-user {
        subscribe: func() -> result<pollable, listen-error>;
        get: func() -> result<user, listen-error>;
    }


    variant listen-error {
        already-listening,
        not-ready,
        closed
    }
    
    listen-user: func() -> result<future-user, listen-error>;
}

world imports {
    import bindings;

    export run: func() -> result;
}