name = "example-basic-typed"
rooms = "AutoCreate"

[debug]
command = "cargo build --target wasm32-wasip2"
output = "target/wasm32-wasip2/debug/example_basic_typed.wasm"

[release]
command = "cargo build --target wasm32-wasip2 --release"
output = "target/wasm32-wasip2/release/example_basic_typed.wasm"
