// This file is generated by maf. Do not edit manually.
export type MafStoresList = {
  count: {
    name: "count";
    select: number | null;
  };
};

export type GeneratedTypes = {
  stores: MafStoresList;
};
