// This file is generated by maf. Do not edit manually.

// prettier-ignore
export type MafStoresList = {
  "count": {
    name: "count";
    select: number | null;
  };
};

// prettier-ignore
export type MafRpcsList = {
  "increment_counter": {
    name: "increment_counter";
    params: number;
    result: number;
  };
};

export type MafApp = {
  __isTyped: true;
  stores: MafStoresList;
  rpcs: MafRpcsList;
};
