[package]
name = "maf"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "^1.0.96"
async-lock = "3.4.0"
futures-util = "0.3.31"
serde = { version = "^1", features = ["derive"] }
serde_json = { version = "^1", default-features = false, features = ["alloc"] }
tokio = { version = "1.44.2", default-features = false, features = ["sync"] }
uuid = { version = "1.16.0", features = ["serde", "v4"] }

# [target."wasm32-wasip2".dependencies]
wit-bindgen = "0.40.0"
wasi = "0.14.2"
