app = "maf-server"

[[vm]]
memory = "1GB"
cpus = 2

[env]
RUST_LOG = "maf_container=info"
AUTO_SHUTDOWN_TIMEOUT = "60"

[build]
dockerfile = "./fly.dockerfile"

[mounts]
source = "bundles"
destination = "/app/bundle"

[http_service]
internal_port = 3000
force_https = true
auto_start_machines = true
auto_restart = true
min_machines_running = 0

[http_service.concurrency]
type = "connections"
hard_limit = 75
soft_limit = 50
