app = "maf-server"

[env]
RUST_LOG = "maf_container=info"
AUTO_SHUTDOWN_TIMEOUT = "60"

[[vm]]
memory = "1GB"
cpus = 2

[build]
dockerfile = "./fly.dockerfile"

[http_service]
internal_port = 3000
force_https = true
auto_start_machines = true
auto_restart = true
min_machines_running = 0

[http_service.concurrency]
type = "connections"
hard_limit = 75
soft_limit = 50
