app = "cobble-server"

[[vm]]
memory = "1GB"
cpus = 2

[env]
RUST_LOG = "cobble_container_host=info"
AUTO_SHUTDOWN_TIMEOUT = "60"

[build]
dockerfile = "./fly.dockerfile"

[mounts]
source = "bundles"
destination = "/app/bundle"

[http_service]
internal_port = 1147
force_https = false
auto_start_machines = true
auto_restart = true
min_machines_running = 0

[http_service.concurrency]
type = "connections"
hard_limit = 5_000
soft_limit = 1_000
