name = "example-basic"
rooms = "AuthenticatedApiRequest"

[debug]
command = "cargo build --target wasm32-wasip2"
output = "target/wasm32-wasip2/debug/example_basic.wasm"

[release]
command = "cargo build --target wasm32-wasip2 --release"
output = "target/wasm32-wasip2/release/example_basic.wasm"
