[package]
name = "{{name}}"
version = "0.1.0"
edition = "2024"

[dependencies]
cobble = "0.1.0-alpha.2"
# To use the latest version, you can use the following instead:
# cobble = { git = "https://github.com/giilbert/cobble" }
# serde is a library for serializing and deserializing data
serde = { version = "^1", features = ["derive"] }

[lib]
crate-type = ["cdylib"] # This is required for Cargo to build the library
