name = "cobble-demo"
rooms = "AutoCreate"

[debug]
command = "cargo build --target wasm32-wasip2"
output = "../../target/wasm32-wasip2/debug/cobble_demo.wasm"

[release]
command = "cargo build --target wasm32-wasip2 --release"
output = "../../target/wasm32-wasip2/release/cobble_demo.wasm"
