name = "maf-demo"
rooms = "AutoCreate"

[debug]
command = "cargo build --target wasm32-wasip2"
output = "./target/wasm32-wasip2/debug/maf_demo.wasm"

[release]
command = "cargo build --target wasm32-wasip2 --release"
output = "./target/wasm32-wasip2/release/maf_demo.wasm"
